routes/web.php
<?php

use Illuminate\Support\Facades\Session;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Ver SQL Optimizador

// DB::Listen(Function($query){
//     echo "<pre>{ $query->sql }</pre>";
//     //echo "<pre>{ $query->time }</pre>";
// });

Route::get('alert', function () { 
	Session::flash('error2', 'hola');
	return view('home');
	 });

Route::get('400', function () { abort(400); });
Route::get('401', function () { abort(401); });
Route::get('403', function () { abort(403); });
Route::get('404', function () { abort(404); });
Route::get('500', function () { abort(500); });
Route::get('504', function () { abort(504); });
Route::get('509', function () { abort(509); });

Route::get('/', function () {
  return redirect('home');
});

Route::get('/invitado', function () {
  return 'Hola';
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/ver/estudiantes', 'HomeController@index')->name('ver.estudiantes');

Route::get('/ver/asignaturas', 'HomeController@asignaturas')->name('ver.asignaturas');

Route::get('/informe/estudiante/crear', 'EstudianteController@informe_crear')->name('informe.crear');

Route::post('/informe/estudiante', 'EstudianteController@informe')->name('informe');


Route::get('/ver/estudiantesByAsignatura/{asignatura}', 'HomeController@estudiantesByAsignatura')->name('ver.estudiantesByAsignatura');

Route::get('/notas/createByDocente/{asignatura}/{estudiante}', 'NotaController@createByDocente')->name('notas.createByDocente');

Route::get('/notas/indexByDocente/{asignatura}/{estudiante}', 'NotaController@indexByDocente')->name('notas.indexByDocente');




Route::resource('usuarios', 'UsersController');

Route::get('usuarios/gen/{id}',[
            'as' => 'usuarios.genUser',
            'uses' => 'UsersController@genUser',
        ]);

Route::get('usuarios/reset/{id}',[
            'as' => 'usuarios.reset.image',
            'uses' => 'UsersController@resetImage',
        ]);



Route::resource('roles', 'RoleController');

Route::post('impersonations', 'ImpersonationController@store')->name('impersonations.store');
Route::delete('impersonations', 'ImpersonationController@destroy')->name('impersonations.destroy');


// Registration Routes...

        // Route::get('register', function () { abort(404); });  //Desactivar Registro
        // Route::post('register', function () { abort(404); });  //Desactivar Registro

// END ADMIN

    Route::resource('departamentos', 'DepartamentoController');
    Route::resource('municipios', 'MunicipioController');








Route::resource('sedes', 'SedeController');

Route::resource('estudiantes', 'EstudianteController');

Route::resource('docentes', 'DocenteController');

Route::resource('asignaturas', 'AsignaturaController');

Route::resource('cursas', 'CursaController');

Route::resource('impartes', 'ImparteController');

Route::resource('logros', 'LogroController');

Route::resource('notas', 'NotaController');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use App\Traits\DatesTranslator;
use App\Notifications\ResetPasswordNotification;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
    use Notifiable, SoftDeletes;
    use DatesTranslator; 

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['nombres', 'apellidos', 'cedula', 'avatar', 'email', 'password', ];
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * Send the password reset notification.
     *
     * @param  string  $token
     * @return void
     */
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPasswordNotification($token));
    }

    /**
     * Relationships
     */
   
    public function roles()
    {
        return $this->belongsToMany('App\Models\Role', 'assigned_roles')->withTimestamps();
    }


    public function docente()
    {
        return $this->hasOne('App\Models\Docente', 'cedula', 'cedula');
    }


    // public function natural()
    // {
    //     return $this->hasOne('App\Models\Natural', 'cedula', 'cedula');
    // }
    /**
     * Functions security
     */
    public function hasRoles(array $roles)
    {        
        return $this->roles->pluck('name')->intersect($roles)->count();        
    }

    public function isAdmin()
    {
        return $this->hasRoles(['admin']);
    }

    public function isMixAdmin()
    {
        return $this->hasRoles(['admin', 'ceo']);
    }  

    public function isWork()
    {
        return $this->hasRoles(['admin', 'ceo', 'secretary']);
    }  

     /**
     * Mutadores & Ascensores
     */     

    public function getFullNameAttribute()
    {
       return $this->nombres . ' ' . $this->apellidos;
    }

     /**
     * seleccionadores
     */
    public static function selUsuario($role){
        $array['']= "seleccione...";
        $modelo = User::all()->toArray();
            foreach ($modelo as $key => $value) {
                if ($value['role']==$role) {
                    $array[$value['id']] = $value['nombres'].' '.$value['apellidos'];
                }                
            }
        return ($array);
    }

}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateUserRequest;
use App\Http\Requests\UpdateUserRequest;
use App\User;
use App\Models\Role;
use Flash;
use Illuminate\Http\Request;
use Mail;
use Illuminate\Support\Facades\Storage;

class UsersController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        // $this->middleware('roles:admin,gerente',['except' => ['edit', 'update']]);
        // $this->middleware([
        //     'auth', 'roles:admin'
        // ]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::with(['roles'])->paginate(15);
        return view('users.index')->with(['users' => $users]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::pluck('display_name', 'id');
        return view('users.create')->with(['roles' => $roles]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateUserRequest $request)
    {
        $input = [
            'nombres'   => $request->nombres,
            'apellidos' => $request->apellidos,
            'cedula'    => $request->cedula,
            'email'     => $request->email,
            'password'  => bcrypt($request->password),
        ];

        $user = (new User)->fill($input);

        if ($request->hasFile('avatar')) 
        {
            $user->avatar = Storage::url( $request->file('avatar')->store('public/avatars') );
        }

        $user->save();

        Flash::success('Usuario registrado correctamente.');

        return redirect(route('usuarios.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        
        try {
            $user =  User::find($id);
        } catch (Exception $e) { /*nothing*/ }

        if (empty($user)) {
            Flash::error('Usuario No se encuentra registrado.');

            return redirect(route('usuarios.index'));
        }
        
        // $this->authorize($user);

        $roles = Role::pluck('display_name', 'id');

        return view('users.edit')->with(['user' => $user, 'roles' => $roles]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function resetImage($id)
    {
        try {
            $user = User::find($id);
        } catch (Exception $e) { /*nothing*/ }

        if (empty($user)) {
            Flash::error('Usuario No se encuentra registrado.');

            return redirect(route('usuarios.index'));
        }

        // $this->authorize($user);

                 
       if ($user->avatar != '/default-profile.png') 
       {
            $photoPath = str_replace('storage', 'public', $user->avatar);

            Storage::delete($photoPath);

        $user->update(['avatar' => '/default-profile.png']);
        
        Flash::success('Avatar Reestablecido.');

       } else {

        Flash::warning('Avatar por defecto.');

       }

        return redirect(route('usuarios.edit', [$id]));
            
        
    }
    public function update(UpdateUserRequest $request, $id)
    {
        
        try {
            $user = User::find($id);
        } catch (Exception $e) { /*nothing*/ }

        if (empty($user)) {
            Flash::error('Usuario No se encuentra registrado.');

            return redirect(route('usuarios.index'));
        }
        
        // $this->authorize($user);

        if ($request->hasFile('avatar')) 
        {           
           if ($user->avatar != '/default-profile.png') 
           {
                $photoPath = str_replace('storage', 'public', $user->avatar);

                Storage::delete($photoPath);
           }

            $user->avatar = Storage::url( $request->file('avatar')->store('public/avatars') );
        }

        $user->update($request->only('cedula', 'nombres', 'apellidos', 'email'));
        
        if (auth()->user()->isMixAdmin()) {
            
            $assignedRoles = $request->roles;

            if (!is_null($request->roles)) {
                foreach ($request->roles as $role) {
                   $assignedRoles[$role] = ['who_user' => \Auth::id()];
                }
            }
            $user->roles()->sync($assignedRoles);

            Flash::success('Usuario actualizado correctamente.');

            return redirect('usuarios');
        }

        
        Flash::success('Usuario actualizado correctamente.');

        return redirect('home');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        try {
            $user = User::find($id);
        } catch (Exception $e) { /*nothing*/ }

        if (empty($user)) {
            Flash::error('Usuario No se encuentra registrado.');

            return redirect(route('usuarios.index'));
        }
        
        // $this->authorize($user);

        $user->delete();

        Flash::success('Usuario eliminado correctamente.');

        return redirect(route('usuarios.index'));
    }

    public function genUser($id)
    {
        $natural = \App\Models\Natural::find($id);

        if (empty($natural->email)) {
            Flash::error('Tercero natural: '. $natural->fullname.' No posee registro de "email" para realizar esta acción.');

            return redirect(route('naturals.index'));
        }


       $result = User::create([
            'nombres'   => $natural->nombres,
            'apellidos' => $natural->apellidos,
            'cedula'    => $natural->cedula,
            'email'     => $natural->email,
            'password'  => bcrypt('FE$T27VISOR'),
        ]);

       $result->roles()->sync([3]);

       try{
            Mail::send('emails.genUser', ['natural' => $natural, 'pass' => 'FE$T27VISOR'], function ($message) use($natural){
     
                $message->from('sistema@transportedigital.com', 'FestSupervisor');
         
                $message->to($natural->email)->subject('Alcaldia de Apartadó');
         
            });
        } catch(\Exception $e) {
            // errors
        }



       Flash::success('Usuario Generado correctamente.');

        return redirect(route('naturals.index'));
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('title', 'Usuarios |')

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-8">
            <h2>Cuentas de usuario</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route('home') }}">Inicio</a>
                </li>
                <li>
                    <a href="{{ route('usuarios.index') }}">Usuarios</a>
                </li>
                <li class="active">
                    <strong>Registrar</strong>
                </li>                        
            </ol>
        </div>
    </div>
    <div class="content">
        <div class="row wrapper wrapper-content animated fadeInRight"> 
            <div class="ibox">
                @include('common.errors')
                <div class="ibox-content">
                    <div class="row">
                        {!! Form::open(['route' => 'usuarios.store', 'enctype' => 'multipart/form-data', 'class' => 'form-horizontal']) !!}

                            @include('users.fields')

                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('css')
    <link rel="stylesheet" href="/src/icheck/skins-flat/green.css">
@endpush

@push('scripts')
 <script src="/src/icheck/icheck.min.js"></script>
 <script>
    $(document).ready(function () {  
         $('input').iCheck({
            checkboxClass: 'icheckbox_flat-green',
            radioClass: 'iradio_flat-green',
            increaseArea: '20%' // optional
        });
    });
    
 </script>
@endpush

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('title', 'Usuarios |')

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-8">
            <h2>Cuentas de usuario</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route('home') }}">Inicio</a>
                </li>
                <li>
                    <a href="{{ route('usuarios.index') }}">Usuarios</a>
                </li>
                <li class="active">
                    <strong>Registrar</strong>
                </li>                        
            </ol>
        </div>
    </div>
   <div class="content">      
       <div class="row wrapper wrapper-content animated fadeInRight">
         <div class="ibox">
                @include('common.errors')
                @include('flash::message')
             <div class="ibox-content">                 
                     {!! Form::model($user, ['route' => ['usuarios.update', $user->id], 'method' => 'patch', 'enctype' => 'multipart/form-data', 'class' => 'form-horizontal']) !!}

                          @include('users.fields')

                     {!! Form::close() !!}  
             </div>
         </div>
        </div>
   </div>
@endsection

@push('css')
    <link rel="stylesheet" href="/src/icheck/skins-flat/green.css">
@endpush

@push('scripts')
 <script src="/src/icheck/icheck.min.js"></script>
 <script>
    $(document).ready(function () {  
         $('input').iCheck({
            checkboxClass: 'icheckbox_flat-green',
            radioClass: 'iradio_flat-green',
            increaseArea: '20%' // optional
        });
    });
    
 </script>
@endpush

resources/views/users/fields.blade.php
<!-- Cedula Field -->
<div class="form-group">
    {!! Form::label('cedula', 'Cédula', ['class' => 'col-sm-2 control-label']) !!}
    <div class="col-sm-10">
        {!! Form::text('cedula', null, ['class' => 'form-control']) !!}
    </div>
</div>

<!-- Nombres Field -->
<div class="form-group">
    {!! Form::label('nombres', 'Nombres', ['class' => 'col-sm-2 control-label']) !!}
    <div class="col-sm-10">
        {!! Form::text('nombres', null, ['class' => 'form-control']) !!}
    </div>
</div>

<!-- Apellidos Field -->
<div class="form-group">
    {!! Form::label('apellidos', 'Apellidos', ['class' => 'col-sm-2 control-label']) !!}
    <div class="col-sm-10">
        {!! Form::text('apellidos', null, ['class' => 'form-control']) !!}
    </div>
</div>

<!-- Email Field -->
<div class="form-group">
    {!! Form::label('email', 'Email', ['class' => 'col-sm-2 control-label']) !!}
    <div class="col-sm-10">
        {!! Form::email('email', null, ['class' => 'form-control']) !!}
    </div>
</div>

<div class="clearfix"></div>

@if (Request::is('usuarios/create'))
    <!-- Password Field -->
    <div class="form-group">
        {!! Form::label('password', 'Contraseña', ['class' => 'col-sm-2 control-label']) !!}
        <div class="col-sm-10">
            {!! Form::password('password', ['class' => 'form-control']) !!}
        </div>
    </div>

    <!-- Password Field -->
    <div class="form-group">
        {!! Form::label('password_confirmation', 'Confirmar Contraseña', ['class' => 'col-sm-2 control-label']) !!}
        <div class="col-sm-10">
            {!! Form::password('password_confirmation', ['class' => 'form-control']) !!}
        </div>
    </div>
@endif

@if (auth()->user()->isAdmin())
    <!-- Roles Field -->
    <div class="form-group">
        {!! Form::label('roles', 'Roles', ['class' => 'col-sm-2 control-label']) !!}
        <div class="col-sm-10">            
            @foreach ($roles as $id => $name)
                <label class="checkbox-inline">  
                @if (isset($user))                    
                    {!! Form::checkbox('roles[]', $id,
                    $user->roles->pluck('id')->contains($id) ? '1' : null
                    ) !!} 
                    {{ $name }}
                @else
                    {!! Form::checkbox('roles[]', $id, false) !!} 
                    {{ $name }}                 
                @endif
                </label>
            @endforeach
        </div>
    </div>
@endif

@unless (Request::is('usuarios/create*'))
<div class="form-group">
    {!! Form::label('avatar', 'Avatar', ['class' => 'col-sm-2 control-label']) !!}
    <div class="col-sm-10">
        @if ($user->avatar != '/default-profile.png')
            <a href="{!! route('usuarios.reset.image', [$user->id]) !!}" data-toggle='tooltip' title='' data-original-title='Restaurar avatar'>
                <img src="{{ $user->avatar }}" class="img-circle" alt="Avatar Image" width="80px" style="margin-bottom: 5px;  border: 3px solid;  border-color: rgba(0,0,0,0.2);">
            </a>
        @else
            <img src="{{ $user->avatar }}" class="img-circle" alt="Avatar Image" width="80px" style="margin-bottom: 5px;  border: 3px solid;  border-color: rgba(0,0,0,0.2);">
        @endif
        
        {!! Form::file('avatar', ['class' => '']) !!}
    </div>
</div>
@endunless


<!-- Submit Field -->

<div class="form-group">
   <div class="col-sm-10 col-sm-offset-2">     
        {!! Form::button('<i class="glyphicon glyphicon-floppy-disk"></i> Guardar', ['type' => 'submit', 'class' => 'btn btn-primary  ']) !!}
        
        @if (auth()->user()->isMixAdmin())
            <a href="{!! route('usuarios.index') !!}" class="btn btn-default  ">Cancelar</a>
        @endif
        
   </div>
 </div>



{{-- @push('css')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.1.1/min/dropzone.min.css">
@endpush --}}
@push('scripts')
{{-- <script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.1.1/min/dropzone.min.js"></script> --}}
  <script>
    $(function () {
        $('input').iCheck({
            checkboxClass: 'icheckbox_square-blue',
            radioClass: 'iradio_square-blue',
            increaseArea: '20%' // optional
        });
    });
  </script>
@endpush

resources/views/users/index.blade.php
@extends('layouts.app')

@section('title', 'Usuarios |')

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-8">
            <h2>Cuentas de usuario</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route('home') }}">Inicio</a>
                </li>
                <li class="active">
                    <strong>Usuarios</strong>
                </li>                        
            </ol>
        </div>
        <div class="col-lg-4">
            <div class="title-action">
                <a href="{!! route('usuarios.create') !!}" class="btn btn-primary"><i class="fa fa-plus"></i> Agregar </a>
            </div>
        </div>
    </div>

    <div class="content">
        <div class="row wrapper wrapper-content animated fadeInRight">            
            <div class="ibox">
                @include('flash::message')
                <div class="ibox-content table-responsive">
                    @if($users->isEmpty())
                        <div class="alert alert-info alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                            <h4><i class="icon fa fa-info"></i>Información</h4>
                           No se encontraron registros de Users en esta consulta.
                        </div>
                    @else
                        @include('users.table')
                        @include('common.paginate', ['records' => $users])   
                    @endif
                </div>
            </div>           
        </div>
    </div>
@endsection

resources/views/users/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Usuario
        </h1>
    </section>
    <div class="content">
        <div class="ibox">
            <div class="ibox-content">
                <div class="row" style="padding-left: 20px">
                    @include('users.show_fields')
                    <a href="{!! route('usuarios.index') !!}" class="btn btn-default">Atrás</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $user->id !!}</p>
</div>

<!-- Nombres Field -->
<div class="form-group">
    {!! Form::label('nombres', 'Nombres:') !!}
    <p>{!! $user->nombres !!}</p>
</div>

<!-- Apellidos Field -->
<div class="form-group">
    {!! Form::label('apellidos', 'Apellidos:') !!}
    <p>{!! $user->apellidos !!}</p>
</div>

<!-- Cedula Field -->
<div class="form-group">
    {!! Form::label('cedula', 'Cedula:') !!}
    <p>{!! $user->cedula !!}</p>
</div>

<!-- Password Field -->
<div class="form-group">
    {!! Form::label('password', 'Password:') !!}
    <p>{!! $user->password !!}</p>
</div>

<!-- Email Field -->
<div class="form-group">
    {!! Form::label('email', 'Email:') !!}
    <p>{!! $user->email !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $user->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $user->updated_at !!}</p>
</div>

resources/views/users/table.blade.php
<table class="table table-hover" id="users-table">
    <thead>
    @if (auth()->user()->isAdmin() && auth()->id() === 1)
        <th>Imper</th>
    @endif
        <th>Avatar</th>
        <th>Cédula</th>
        <th>Nombres</th>
        <th>Apellidos</th>
        <th>Email</th>
        <th>Roles</th>
        <th>Docente</th>
        <th colspan="3" class="text-right">Acciones</th>
    </thead>
    <tbody>
    @foreach($users as $user)
        <tr>
            <td>
                @if (auth()->user()->isAdmin() && auth()->id() === 1 && $user->id != 1)                    
                        {!! Form::open(['route' => ['impersonations.store'], 'method' => 'POST']) !!}
                            {!! Form::hidden('user_id',$user->id) !!}
                            {!! Form::button('<i class="fa fa-user-secret"></i>', [
                                'type' => 'submit',
                                'class' => 'btn btn-default btn-sm',
                                'title' => 'Personificar',
                                'style' => 'position'
                                ]) !!}                        

                    {!! Form::close() !!}
                @else
                    @if (auth()->user()->isAdmin() && auth()->id() === 1 && $user->id === 1)
                        <a href="#" class="btn btn-default btn-sm" disabled><i class="fa fa-lock"></i></a>
                    @endif
                @endif

            </td>
            <td title="Ultima actualización: {{ $user->created_at->diffForHumans() }}">
                @if (!is_null($user->avatar))
                    <img src="{{ $user->avatar }}" alt="Profile" class="img-circle" width="40px">               
                @endif               
                
            </td>
            <td>{!! number_format($user->cedula, 0, '.', '.' ) !!}</td>
            <td>{!! $user->nombres !!}</td>
            <td>{!! $user->apellidos !!}</td>
            <td>{!! $user->email !!}</td>
            <td>{{  $user->roles->pluck('display_name')->implode(', ') }}</td>
            <td>{!!  optional($user->docente)->nombres ? '<span class="label label-primary">Si</span>' : '<span class="label label-default">No</span>' !!}</td>
            <td width="90px">
                <div class='pull-right'>
                    {!! Form::open(['route' => ['usuarios.destroy', $user->id], 'method' => 'delete']) !!}
                       {{--  <a href="{!! route('users.show', [$user->id]) !!}" class='btn btn-default btn-sm'><i class="glyphicon glyphicon-eye-open"></i></a> --}}
                        <a href="{!! route('usuarios.edit', [$user->id]) !!}" class='btn btn-default btn-sm' data-toggle='tooltip' title='' data-original-title='Editar'><i class="zmdi zmdi-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
                            'type' => 'submit',
                            'class' => 'btn btn-outline btn-danger btn-sm',
                            'onclick' => "return confirm('¿Confirma que desea eliminar?')",
                            'title' => 'Eliminar'
                            ]) !!}
                    {!! Form::close() !!}
                    
                </div>
            </td>
        </tr>
    @endforeach
    </tbody>
</table>