routes/web.php
<?php

use Illuminate\Support\Facades\Session;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Ver SQL Optimizador

// DB::Listen(Function($query){
//     echo "<pre>{ $query->sql }</pre>";
//     //echo "<pre>{ $query->time }</pre>";
// });

Route::get('alert', function () { 
	Session::flash('error2', 'hola');
	return view('home');
	 });

Route::get('400', function () { abort(400); });
Route::get('401', function () { abort(401); });
Route::get('403', function () { abort(403); });
Route::get('404', function () { abort(404); });
Route::get('500', function () { abort(500); });
Route::get('504', function () { abort(504); });
Route::get('509', function () { abort(509); });

Route::get('/', function () {
  return redirect('home');
});

Route::get('/invitado', function () {
  return 'Hola';
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/ver/estudiantes', 'HomeController@index')->name('ver.estudiantes');

Route::get('/ver/asignaturas', 'HomeController@asignaturas')->name('ver.asignaturas');

Route::get('/informe/estudiante/crear', 'EstudianteController@informe_crear')->name('informe.crear');

Route::post('/informe/estudiante', 'EstudianteController@informe')->name('informe');


Route::get('/ver/estudiantesByAsignatura/{asignatura}', 'HomeController@estudiantesByAsignatura')->name('ver.estudiantesByAsignatura');

Route::get('/notas/createByDocente/{asignatura}/{estudiante}', 'NotaController@createByDocente')->name('notas.createByDocente');

Route::get('/notas/indexByDocente/{asignatura}/{estudiante}', 'NotaController@indexByDocente')->name('notas.indexByDocente');




Route::resource('usuarios', 'UsersController');

Route::get('usuarios/gen/{id}',[
            'as' => 'usuarios.genUser',
            'uses' => 'UsersController@genUser',
        ]);

Route::get('usuarios/reset/{id}',[
            'as' => 'usuarios.reset.image',
            'uses' => 'UsersController@resetImage',
        ]);



Route::resource('roles', 'RoleController');

Route::post('impersonations', 'ImpersonationController@store')->name('impersonations.store');
Route::delete('impersonations', 'ImpersonationController@destroy')->name('impersonations.destroy');


// Registration Routes...

        // Route::get('register', function () { abort(404); });  //Desactivar Registro
        // Route::post('register', function () { abort(404); });  //Desactivar Registro

// END ADMIN

    Route::resource('departamentos', 'DepartamentoController');
    Route::resource('municipios', 'MunicipioController');








Route::resource('sedes', 'SedeController');

Route::resource('estudiantes', 'EstudianteController');

Route::resource('docentes', 'DocenteController');

Route::resource('asignaturas', 'AsignaturaController');

Route::resource('cursas', 'CursaController');

Route::resource('impartes', 'ImparteController');

Route::resource('logros', 'LogroController');

Route::resource('notas', 'NotaController');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<html>
<head>
    <meta charset="utf-8">
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <title>@yield('title') HarvardColege</title>


    <link rel="stylesheet" href="{!! asset('css/vendor.css') !!}" />
    <link rel="stylesheet" href="{!! asset('css/app.css') !!}" />
    {!! Html::style('/dependencia_local/bootstrap-xlgrid.min.css') !!}
    <link href="/src/css/select2/4.0.4/select2.min.css" rel="stylesheet" />
    {!! Html::style('/css/select2-lte.css') !!}
    <link rel="stylesheet" href="/src/css/datapicker/datepicker3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">

     <!-- skin icheck -->
    @yield('css')
    @stack('css')
    <link rel="stylesheet" href="/css/main.css">

</head>
<body>

  <!-- Wrapper-->
    <div id="wrapper">

        <!-- Navigation -->
        @include('layouts.navigation')

        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg">

            <!-- Page wrapper -->
            @include('layouts.topnavbar')

            <!-- Main view  -->
            @yield('content')

            <!-- Footer -->
            @include('layouts.footer')

        </div>
        <!-- End page wrapper-->

    </div>
    <!-- End wrapper-->

<script src="{!! asset('js/app.js') !!}" type="text/javascript"></script>
<script src="/src/js/select2/4.0.4/select2.min.js"></script>
<!-- datepicker  -->
    {!! HTML::script('/src/js/datapicker/bootstrap-datepicker.js') !!}
    <!-- datepicker español -->
    {!! HTML::script('/src/js/datapicker/locales/bootstrap-datepicker.es.js') !!}
    
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
{!! HTML::script('/js/main.js') !!}


@section('scripts')
@show
@yield('scripts')
@stack('scripts')

@if ( config('app.env') == 'production' )
    @include('common.partial_chat')    
@endif
@include('common.alert-toastr')


</body>
</html>

resources/views/layouts/app_docente.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<html>
<head>
    <meta charset="utf-8">
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <title>@yield('title') HarvardColege</title>


    <link rel="stylesheet" href="{!! asset('css/vendor.css') !!}" />
    <link rel="stylesheet" href="{!! asset('css/app.css') !!}" />
    {!! Html::style('/dependencia_local/bootstrap-xlgrid.min.css') !!}
    <link href="/src/css/select2/4.0.4/select2.min.css" rel="stylesheet" />
    {!! Html::style('/css/select2-lte.css') !!}
    <link rel="stylesheet" href="/src/css/datapicker/datepicker3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">

     <!-- skin icheck -->
    @yield('css')
    @stack('css')
    <link rel="stylesheet" href="/css/main.css">

</head>
<body class="top-navigation">

  <!-- Wrapper-->
    <div id="wrapper">

        <!-- Navigation -->
        {{-- @ include('layouts.navigation') --}}

        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg">

            <!-- Page wrapper -->
            @include('layouts.menu_docente')

            <!-- Main view  -->
            @yield('content')

            <!-- Footer -->
            @include('layouts.footer')

        </div>
        <!-- End page wrapper-->

    </div>
    <!-- End wrapper-->

<script src="{!! asset('js/app.js') !!}" type="text/javascript"></script>
<script src="/src/js/select2/4.0.4/select2.min.js"></script>
<!-- datepicker  -->
    {!! HTML::script('/src/js/datapicker/bootstrap-datepicker.js') !!}
    <!-- datepicker español -->
    {!! HTML::script('/src/js/datapicker/locales/bootstrap-datepicker.es.js') !!}
    
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
{!! HTML::script('/js/main.js') !!}


@section('scripts')
@show
@yield('scripts')
@stack('scripts')

@if ( config('app.env') == 'production' )
    @include('common.partial_chat')    
@endif
@include('common.alert-toastr')


</body>
</html>

resources/views/layouts/app_informe.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<html>
<head>
    <meta charset="utf-8">
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <title>@yield('title') HarvardColege</title>


    <link rel="stylesheet" href="{!! asset('css/vendor.css') !!}" />
    <link rel="stylesheet" href="{!! asset('css/app.css') !!}" />
    {!! Html::style('/dependencia_local/bootstrap-xlgrid.min.css') !!}
    <link href="/src/css/select2/4.0.4/select2.min.css" rel="stylesheet" />
    {!! Html::style('/css/select2-lte.css') !!}
    <link rel="stylesheet" href="/src/css/datapicker/datepicker3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">

     <!-- skin icheck -->
    @yield('css')
    @stack('css')
    <link rel="stylesheet" href="/css/main.css">

</head>
<body class="top-navigation" >

  <!-- Wrapper-->
    <div id="wrapper">

        <!-- Navigation -->
        {{-- @ include('layouts.navigation') --}}

        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg">

            <!-- Page wrapper -->
            @include('layouts.menu_informe')

            <!-- Main view  -->
            @yield('content')

            <!-- Footer -->
            @include('layouts.footer')

        </div>
        <!-- End page wrapper-->

    </div>
    <!-- End wrapper-->

<script src="{!! asset('js/app.js') !!}" type="text/javascript"></script>
<script src="/src/js/select2/4.0.4/select2.min.js"></script>
<!-- datepicker  -->
    {!! HTML::script('/src/js/datapicker/bootstrap-datepicker.js') !!}
    <!-- datepicker español -->
    {!! HTML::script('/src/js/datapicker/locales/bootstrap-datepicker.es.js') !!}
    
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
{!! HTML::script('/js/main.js') !!}


@section('scripts')
@show
@yield('scripts')
@stack('scripts')

@if ( config('app.env') == 'production' )
    @include('common.partial_chat')    
@endif
@include('common.alert-toastr')


</body>
</html>

resources/views/layouts/app_remote_dep.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Transeba | FestCar</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.2/css/select2.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.3.3/css/AdminLTE.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.3.3/css/skins/_all-skins.min.css">
    <!-- Linear Icons -->
    <link rel="stylesheet" href="https://cdn.linearicons.com/free/1.0.0/icon-font.min.css">
    <!-- Simple Line icons -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Animsitun -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/animsition/4.0.2/css/animsition.min.css">
    <!-- datepicker -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker.min.css">
    <!-- select2 -->
    <!--
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
    -->
    <!-- FLATICONS Custom -->
    {!! Html::style('/css/flaticon_bus/flaticon.css') !!}

    <!-- CSS PRINCIPAL WEB PAGE CUSTOM-->
    {!! Html::style('/css/main.css') !!}
    <!-- FavICONS ================================================== -->

        <link rel="apple-touch-icon" sizes="57x57" href="{!! url('/favicon/apple-icon-57x57.png') !!}">
        <link rel="apple-touch-icon" sizes="60x60" href="{!! url('/favicon/apple-icon-60x60.png') !!}">
        <link rel="apple-touch-icon" sizes="72x72" href="{!! url('/favicon/apple-icon-72x72.png') !!}">
        <link rel="apple-touch-icon" sizes="76x76" href="{!! url('/favicon/apple-icon-76x76.png') !!}">
        <link rel="apple-touch-icon" sizes="114x114" href="{!! url('/favicon/apple-icon-114x114.png') !!}">
        <link rel="apple-touch-icon" sizes="120x120" href="{!! url('/favicon/apple-icon-120x120.png') !!}">
        <link rel="apple-touch-icon" sizes="144x144" href="{!! url('/favicon/apple-icon-144x144.png') !!}">
        <link rel="apple-touch-icon" sizes="152x152" href="{!! url('/favicon/apple-icon-152x152.png') !!}">
        <link rel="apple-touch-icon" sizes="180x180" href="{!! url('/favicon/apple-icon-180x180.png') !!}">
        <link rel="icon" type="image/png" sizes="192x192"  href="{!! url('/favicon/android-icon-192x192.png') !!}">
        <link rel="icon" type="image/png" sizes="32x32" href="{!! url('/favicon/favicon-32x32.png') !!}">
        <link rel="icon" type="image/png" sizes="96x96" href="{!! url('/favicon/favicon-96x96.png') !!}">
        <link rel="icon" type="image/png" sizes="16x16" href="{!! url('/favicon/favicon-16x16.png') !!}">
        <link rel="manifest" href="{!! url('/favicon/manifest.json') !!}">
        <meta name="msapplication-TileColor" content="#ffffff') !!}">
        <meta name="msapplication-TileImage" content="{!! url('/favicon//ms-icon-144x144.png') !!}">
        <meta name="theme-color" content="#ffffff">
        <!-- favicons -->

    @yield('css')
</head>
<style type="text/css">
    
.skin-blue .main-header .navbar {
    background: #0095d8 !important;
    background: -moz-linear-gradient(left,  #0095d8 0%, #00b0a3 100%) !important;
    background: -webkit-linear-gradient(left,  #0095d8 0%,#00b0a3 100%) !important;
    background: linear-gradient(to right,  #0095d8 0%,#00b0a3 100%) !important;
    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#0095d8', endColorstr='#00b0a3',GradientType=1 ) !important;

}
.skin-blue .main-header .logo {
    background: #0095D8;
}
.skin-blue .main-header li.user-header {
    background: #00B0A3;
}
  
</style>

<body class="skin-blue sidebar-mini">
@if (!Auth::guest())
    <div class="wrapper">
        <!-- Main Header -->
        <header class="main-header">

            <!-- Logo -->
            <a href="#" class="logo">
                <span class="logo-mini"><b>T</b>RS</span>
                <span class="logo-lg"><b>T</b>ranseba</span>
            </a>

            <!-- Header Navbar -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- User Account Menu -->
                        <li class="dropdown user user-menu">
                            <!-- Menu Toggle Button -->
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <!-- The user image in the navbar-->
                                <img  src="{{ asset('/multimedia/profiles/default.png') }}"
                                     class="user-image" alt="imagen de usuario"/>
                                <!-- hidden-xs hides the username on small devices so only the image appears. -->
                                <span class="hidden-xs">{!! Auth::user()->nombres !!}</span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- The user image in the menu -->
                                <li class="user-header">
                                    <img  src="{{ asset('/multimedia/profiles/default.png') }}"
                                         class="img-circle" alt="Imagen de usuario"/>
                                    <p>
                                        {!! Auth::user()->fullname !!}

                                        <small>Miembro desde {!! Auth::user()->created_at->format('M. Y') !!}</small>
                                        <small>({!! ucwords(Auth::user()->role) !!})</small>
                                    </p>
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="#" class="btn btn-default btn-flat">Perfil</a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="{!! url('/logout') !!}" class="btn btn-default btn-flat">Cerrar session</a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>

        <!-- Left side column. contains the logo and sidebar -->
        @include('layouts.sidebar')
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
        
            @yield('content')
        
            
        </div>

        <!-- Main Footer -->
        <footer class="main-footer" style="max-height: 100px;text-align: center">
            <strong>Copyright © 2017 <a href="">FestCar</a>.</strong> Todos los derechos reservados.
        </footer>

    </div>
@else
<!-- USUARIO O INVITADO -->
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{!! url('/') !!}">
                    Invitado: {!! Auth::guest() !!}
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    <li><a href="{!! url('/home') !!}">Home</a></li>
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    <li><a href="{!! url('/login') !!}">Login</a></li>
                    <li><a href="{!! url('/register') !!}">Register</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div id="page-content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    @yield('content')
                </div>
            </div>
        </div>
    </div>
    @endif

    <!-- jQuery 2.1.4 -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.2/js/select2.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/icheck.min.js"></script>

    <!-- AdminLTE App -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.3.3/js/app.min.js"></script>
    <!-- Vue.js -->
    <!-- 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.3.0/vue.js" ></script>
    -->
    <!-- select2 -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
    <!-- select2 español -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/i18n/es.js"></script>
    <!-- datepicker  -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.min.js"></script>
    <!-- datepicker español -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/locales/bootstrap-datepicker.es.min.js"></script>

    <!-- input mask -->
    {{ HTML::script('/js/jquery.inputmask.bundle.min.js') }}
    <!-- Animsition -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/animsition/4.0.2/js/animsition.min.js"></script>
     <!-- Animsition ini -->
    <script type="text/javascript">
        $(document).ready(function() {
          $(".animsition").animsition({
            inClass: 'fade-in',
            outClass: 'fade-out',
            inDuration: 1500,
            outDuration: 800,
            linkElement: '.animsition-link',
            // e.g. linkElement: 'a:not([target="_blank"]):not([href^="#"])'
            loading: true,
            loadingParentElement: 'body', //animsition wrapper element
            loadingClass: 'animsition-loading',
            loadingInner: '', // e.g '<img src="loading.svg" />'
            timeout: false,
            timeoutCountdown: 5000,
            onLoadEvent: true,
            browser: [ 'animation-duration', '-webkit-animation-duration'],
            // "browser" option allows you to disable the "animsition" in case the css property in the array is not supported by your browser.
            // The default setting is to disable the "animsition" in a browser that does not support "animation-duration".
            overlay : false,
            overlayClass : 'animsition-overlay-slide',
            overlayParentElement : 'body',
            transition: function(url){ window.location.href = url; }
          });

          console.log('Welcome To FestCar - PowerBy XS EDUARD');
        });
    </script>
     <!-- Animsition end ini -->
    @yield('scripts')
</body>
</html>

resources/views/layouts/flash.blade.php
<div v-if="flashMessage" class="alert alert-@{{ flashType }}">
	<b>@{{ flashMessage }}</b>
	<hr v-if="$validation.errors">
	<validator-errors :component="'custom-error'" :validation="$validation"></validator-errors>
</div>

resources/views/layouts/footer.blade.php
<div class="footer">
    <div class="pull-right">
        <i class="fa fa-star"></i>
    </div>
    <div>
        <strong>Copyright © 2017</strong> <a href="https://transportedigital.com">HarvardColege</a> Technologies. All rights reserved.
    </div>
</div>

resources/views/layouts/menu.blade.php
<li class="{{ Request::is('home*') ? 'active' : '' }}">
    <a href="{!! url('/home') !!}"><i class="fa fa-home"></i><span class="nav-label">Inicio</span></a>
</li>
<li class="{{ Request::is('usuarios*') ? 'active' : '' }}">
    <a href="{!! route('usuarios.index') !!}" class="animsition-link"><i class="zmdi zmdi-accounts-add"></i><span class="nav-label">Cuentas de Usuario</span></a>
</li>

<li class="{{ Request::is('departamentos*') ? 'active' : '' }}">
    <a href="{!! route('departamentos.index') !!}"><span class="nav-label">Departamentos</span></a>
</li>
<li class="{{ Request::is('municipios*') ? 'active' : '' }}">
    <a href="{!! route('municipios.index') !!}"><span class="nav-label">Municipios</span></a>
</li>
<li class="{{ Request::is('roles*') ? 'active' : '' }}">
    <a href="{!! route('roles.index') !!}"><span class="nav-label">Roles</span></a>
</li>
<li class="{{ Request::is('sedes*') ? 'active' : '' }}">
    <a href="{!! route('sedes.index') !!}"><i class="fa fa-arrow-right"></i><span>Sedes</span></a>
</li>

<li class="{{ Request::is('estudiantes*') ? 'active' : '' }}">
    <a href="{!! route('estudiantes.index') !!}"><i class="fa fa-arrow-right"></i><span>Estudiantes</span></a>
</li>

<li class="{{ Request::is('docentes*') ? 'active' : '' }}">
    <a href="{!! route('docentes.index') !!}"><i class="fa fa-arrow-right"></i><span>Docentes</span></a>
</li>

<li class="{{ Request::is('asignaturas*') ? 'active' : '' }}">
    <a href="{!! route('asignaturas.index') !!}"><i class="fa fa-arrow-right"></i><span>Asignaturas</span></a>
</li>

<li class="{{ Request::is('cursas*') ? 'active' : '' }}">
    <a href="{!! route('cursas.index') !!}"><i class="fa fa-arrow-right"></i><span>Asignar Asignaturas (Estudiantes)</span></a>
</li>

<li class="{{ Request::is('impartes*') ? 'active' : '' }}">
    <a href="{!! route('impartes.index') !!}"><i class="fa fa-arrow-right"></i><span>Docente Imparte Asignatura</span></a>
</li>

<li class="{{ Request::is('logros*') ? 'active' : '' }}">
    <a href="{!! route('logros.index') !!}"><i class="fa fa-arrow-right"></i><span>Logros</span></a>
</li>

<li class="{{ Request::is('notas*') ? 'active' : '' }}">
    <a href="{!! route('notas.index') !!}"><i class="fa fa-edit"></i><span>Notas</span></a>
</li>

<li class="{{ Request::is('notas*') ? 'active' : '' }}">
    <a href="{!! route('informe.crear') !!}"><i class="fa fa-arrow-right"></i><span>Informe</span></a>
</li>

resources/views/layouts/navigation.blade.php
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <span>
                        <img alt="Avatar" class="img-circle" width="48px" src="{{ auth()->user()->avatar }}">
                    </span>
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="clear">
                            <span class="block m-t-xs">
                                <strong class="font-bold">{!! Auth::user()->nombres !!}</strong>
                            </span>
                            <span class="text-muted text-xs block"> 
                                {{  Auth::user()->roles->pluck('display_name')->implode(', ') }} 
                                <b class="caret"></b>
                            </span>
                        </span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a href="{{ route('usuarios.edit', auth()->id()) }}"> Perfil</a></li>
                        <li><a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"> Salir</a></li>
                    </ul>
                </div>
                <div class="logo-element">
                   FC
                </div>
            </li>
            @include('layouts.menu')
        </ul>

    </div>
</nav>